project:
  type: book

book:
  title: "Stat 3702 Project (testing only)"
  author: "Joyce Robbins"
  date: today
  repo-url: https://github.com/jtr13/testproject
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - charlene_nyc_restaurant_data_sample.qmd
    - Dany.qmd
    - Jade.qmd
    - Loadingdata.qmd
    - PennyHuang.qmd
    - ShrinaCoolItProject.qmd
    - Abisola.qmd
    - ziroudata.qmd
    - Alexander.qmd
  
format:
  html:
    theme: [default, style/edav3.scss]
    highlight-style: style/joyce.theme
    callout-icon: false
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 70%
    
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: true

editor: source
